### ISSUE TITLE
form_builder_validator is not compatible with intl. 0.19.0

### ISSUE THREAD

**Issue by iKK001** [flutter-form-builder-ecosystem/form_builder_validators#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Web
- [ ] Windows

### Flutter doctor

not needed

### Minimal code example

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  form_builder_validators: ^9.1.0
```

### Current Behavior

Because form_builder_validators >=9.1.0 depends on intl ^0.18.1 and my_app depends on intl ^0.19.0, form_builder_validators >=9.1.0 is forbidden.

### Expected Behavior

form_builder_validator should be compatible with intl. 0.19.0

### Steps To Reproduce

add intl: ^0.19.0 to your pubscpec.yaml dependencies...

**Comment by deandreamatias** [comment]
Flutter SDK on 3.16.x depends on intl 0.19.0?

**Comment by iKK001** [comment]
@deandreamatias, not sure if I understand your question.

The reason I pinpoint that compatibility is not that I am interested in finding out what version works with what dependency exactly for how long. I am interested in using the newest packages for my new App. And if I find a package that is not catching up with its sub-packages, then I will always pinpoint the incompatibiltiy.

**Comment by deandreamatias** [comment]
If you see the package [flutter_localizations](https://github.com/flutter/flutter/blob/b0366e0a3f089e15fd89c97604ab402fe26b724c/packages/flutter_localizations/pubspec.yaml#L11) that use the dependency intl, on Flutter stable version, use de version number 0.18.1.
So, if I upgrade the dependency to 0.19.x, the form_builder_validator will be not build because flutter sdk use the 0.18.1 version

**Comment by iKK001** [comment]
ah I understand , I did not see that - it makes sense then to wait with intl 0.19.x until flutter sdk also uses it.   Sorry did not want to stress things...

**Comment by satvikreddy** [comment]
Any update on this? Many packages now depend on intl ^0.19.0
The limitation of form_builder_validators is making many other packages unusable :(

**Comment by ch-arslan-kip-tm** [comment]
> Flutter SDK on 3.16.x depends on intl 0.19.0?

Now - yes

https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L14

**Comment by ariefsn** [comment]
you can try this for temporary. update the pubspec.
```yaml
  form_builder_validators:
    git:
      url: https://github.com/ariefsn/form_builder_validators
      ref: intl-v0.19.0
```
